# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
matrix:
  fast_finish: true
before_script:
  - curl -OL http://gmsh.info/bin/Linux/gmsh-git-Linux64-sdk.tgz
  - tar xfv gmsh-git-Linux64-sdk.tgz
  - GMSHROOT=`pwd`/gmsh-git-Linux64-sdk
  - export PATH=$PATH:$GMSHROOT/bin
notifications:
  email:
    on_success: never
    on_failure: always
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
